### ISSUE TITLE
Relative paths in linux-dpdk should be replaced 

### ISSUE THREAD

**Issue by Bill-Fischofer-Linaro** [Linaro/odp#130]
Many include paths in linux-dpdk make long relative references that assume a fixed directory structure. This will cause problems with future directory restructure and should be replaced with more symbolic references that are resolved at config time.

**Comment by Bill-Fischofer-Linaro** [comment]
This comment is associated with PR https://github.com/Linaro/odp/pull/128

**Comment by lumag** [comment]
I would recommend against using so many symlinks instead. I'd suggest using include paths and directory variables to reference linux-generic and subdirs.

**Comment by Bill-Fischofer-Linaro** [comment]
Closing this as it is unique to Caterpillar, which is now discontinued.
