### ISSUE TITLE
Modular framework: Simplify calling the APIs of an active module

### ISSUE THREAD

**Issue by nagarahalli** [Linaro/odp#146]
With the current modular framework, the public APIs of the active module are called as shown below:

int odp_queue_term_global(void)
{
	odp_queue_module_t *mod =
		odp_subsystem_active_module(queue, mod);

	ODP_ASSERT(mod);
	ODP_ASSERT(mod->base.term_global);

	return mod->base.term_global();
}

This can be improved further in the following ways:

1) Provide a macro/API to replace the body
2) The macro 'odp_subsystem_active_module' results in accessing the structure 'odp_subsystem_t', loading a lot of data which is not required in data plane. It would be good to store the 'active' module pointer outside of the 'odp_subsystem_t' structure so that in the data plane, unwanted data is not loaded in the cache.
This can be extended further to club the active modules of all ODP components in an array.

**Comment by Bill-Fischofer-Linaro** [comment]
Closing this as it is unique to Caterpillar, which is now discontinued.
