### ISSUE TITLE
TODO: remove temporary flags for pktio modules linkage

### ISSUE THREAD

**Issue by heyi-linaro** [Linaro/odp#184]
In https://github.com/Linaro/odp/pull/139#discussion_r139837889

For each pktio ops module, to make sure it links into ODP application, it adds temporary flag variable in each module and set it in initial routine.

In the future with Makefile re-organization these variables would be removed and modules will be linked with --whole-archive or --no-as-needed linker options or dynamically loaded.

**Comment by lumag** [comment]
Please double-check static linking path, when implementing these changes.

**Comment by Bill-Fischofer-Linaro** [comment]
Closing this as it is unique to Caterpillar, which is now discontinued.
