### ISSUE TITLE
./bootstrap throws warnings

### ISSUE THREAD

**Issue by nagarahalli** [Linaro/odp#206]
honnag01@ubuntu:~/api-next/odp$ ./bootstrap
+ aclocal -I config -I m4
./test/linux-dpdk/m4/configure.m4:1: warning: file `test/linux-generic/m4/performance.m4' included several times
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
./test/linux-dpdk/m4/configure.m4:1: the top level
./test/linux-dpdk/m4/configure.m4:1: warning: file `test/linux-generic/m4/performance.m4' included several times
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
./test/linux-dpdk/m4/configure.m4:1: the top level
+ libtoolize --copy
+ autoheader
./test/linux-dpdk/m4/configure.m4:1: warning: file `test/linux-generic/m4/performance.m4' included several times
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
./test/linux-dpdk/m4/configure.m4:1: the top level
+ automake --add-missing --copy --warnings=all
./test/linux-dpdk/m4/configure.m4:1: warning: file `test/linux-generic/m4/performance.m4' included several times
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
./test/linux-dpdk/m4/configure.m4:1: the top level
+ autoconf --force
./test/linux-dpdk/m4/configure.m4:1: warning: file `test/linux-generic/m4/performance.m4' included several times
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
./test/linux-dpdk/m4/configure.m4:1: the top level

**Comment by Bill-Fischofer-Linaro** [comment]
I don't see this on the current api-next. This appears to be an artifact introduced by the attempted merge? The base cloud-dev branch doesn't see this either.

```
bill@Ubuntu64:~/linaro/api-next$ ./bootstrap
+ aclocal -I config -I m4
+ libtoolize --copy
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ autoheader
+ automake --add-missing --copy --warnings=all
configure.ac:59: installing './ar-lib'
configure.ac:26: installing './compile'
configure.ac:61: installing './config.guess'
configure.ac:61: installing './config.sub'
configure.ac:22: installing './install-sh'
configure.ac:22: installing './missing'
example/classifier/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
+ autoconf --force
bill@Ubuntu64:~/linaro/api-next$ 
```

**Comment by nagarahalli** [comment]
I think I should have been more clear, yes, this issue applies only to PR #207.

**Comment by Bill-Fischofer-Linaro** [comment]
I think this would be better posted as a review comment to PR #207 then. Issues are for to-do type items.

The proper issue in this case would be why didn't Travis flag this error when it tested that PR? Good that you caught it manually.

**Comment by nagarahalli** [comment]
I have captured it in the cover letter for the PR #207 already.

**Comment by lumag** [comment]
@nagarahalli @heyi-linaro as #321 was merged you might want to rewrite DPDK m4 files to use provided macros.

**Comment by Bill-Fischofer-Linaro** [comment]
Closing this issue as it seems unique to Caterpillar, which is now discontinued.
