### ISSUE TITLE
IPsec SA may be used before fully initialized

### ISSUE THREAD

**Issue by JannePeltonen** [Linaro/odp#423]
There appears to be thread synchronization problem in inbound IPsec SA creation when SA lookup offload is used.

odp_ipsec_sa_create() starts with ipsec_sa_reserve() that reserves a free SA entry and marks it non-free. At this point, before odp_ipsec_sa_create() have completed, another thread may invoke odp_ipsec_in() without an explicit SA, asking ODP to look up the SA.

odp_ipsec_in() indirectly calls _odp_ipsec_sa_lookup() which treats the SA that is still being created as a valid SA and, depending on how far the SA initialization has gone or what the leftover values in the SA are, may decide that the packet matches the SA. In that case subsequent steps would use the SA (e.g. invoke a crypto operation) before the SA creation is done (e.g. crypto session created).

There is no similar problem when SA lookup is not offloaded to ODP since an application is supposed to ensure that SA creation is complete and visible to another thread before using the SA in the other thread.

**Comment by lumag** [comment]
@JannePeltonen thanks for pointing this out. Could you please move this to bugzilla, while I work on these two items.

**Comment by JannePeltonen** [comment]
Reported as bug 3594.
