### ISSUE TITLE
IPsec SA lookup may leave extra SAs locked

### ISSUE THREAD

**Issue by JannePeltonen** [Linaro/odp#424]
If an application has created more than one SA with the same SPI and with ODP_IPSEC_LOOKUP_SPI lookup mode, _odp_ipsec_sa_lookup() matches the last SA it sees but leaves all of them locked.

Such SA configuration does not seem to make much sense but is allowed in the ODP API if the application sets the spi_overlap config bit.

I suggest adding this in the ODP_IPSEC_LOOKUP_SPI branch as well:
        if (NULL != best)
                _odp_ipsec_sa_unuse(best);

**Comment by Bill-Fischofer-Linaro** [comment]
Please open this as a bug. Thanks.

**Comment by JannePeltonen** [comment]
Reported as bug 3595.
