### ISSUE TITLE
Low VALE performance

### ISSUE THREAD

**Issue by jmtilli** [Linaro/odp#520]
I have used ODP a lot with VALE and have found that performance is suboptimal when compared to what you can obtain when using netmap directly without ODP.

How to reproduce this:

    scapy
    >>> wrpcap("1414.pcap", Ether()/IP()/UDP()/((1400-20-8)*"\0"))

Now you have a file named 1414.pcap.

Then clone https://github.com/jmtilli/pptk and compile with netmap following the instructions of README.md. You need to edit opts.mk according to those instructions (the file opts.mk does not exist unless you have typed "make", which will create it as an empty file).

Now, I started the packet generator program with:

    sudo ./pptk/netmap/netmapreplay vale0:0 1414.pcap

And the packet sink program with:

    sudo ./pptk/netmap/netmaprecv vale1:0

And then compared my l2fwd application:

    sudo ./pptk/netmap/netmapfwd vale0:1 vale1:1

With odp_l2fwd_simple:

    sudo odp_l2fwd_simple vale0:1 vale1:1 01:02:03:04:05:06 07:08:09:0a:0b:0c

On the machine on which I'm currently writing this bug report, I have ODP v1.18.0.0 and pptk 5a549f14bb1ee0923568ca5b3236bbf0e0829a26.

I also made the following change to pptk to make netmapfwd of pptk comparable with ODP:

    diff --git a/netmap/netmapfwd.c b/netmap/netmapfwd.c
    index a16ea8b..4f911d8 100644
    --- a/netmap/netmapfwd.c
    +++ b/netmap/netmapfwd.c
    @@ -27,8 +27,10 @@ int main(int argc, char **argv)
       }
     
       memset(&nmr, 0, sizeof(nmr));
    +#if 0
       nmr.nr_rx_slots = 256;
       nmr.nr_tx_slots = 64;
    +#endif
       dlnmd = nm_open(argv[1], &nmr, 0, NULL);
       if (dlnmd == NULL)
       {
    @@ -36,8 +38,10 @@ int main(int argc, char **argv)
         exit(1);
       }
       memset(&nmr, 0, sizeof(nmr));
    +#if 0
       nmr.nr_rx_slots = 256;
       nmr.nr_tx_slots = 64;
    +#endif
       ulnmd = nm_open(argv[2], &nmr, 0, NULL);
       if (ulnmd == NULL)
       {

Now, my expectation would be for ODP to have minimal overhead when compared with netmap. However, with 1414.pcap ODP has on the test machine (Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz) performance of about 2.2 MPPS (25 Gbps) and my own netmapfwd has performance of about 4-4.5 MPPS (45-50 Gbps). This figure of my own netmapfwd was obtained with the patch to remove setting of nr_rx_slots and nr_tx_slots to the most optimal values.

I also tried:

    scapy
    >>> wrpcap("ethermin.pcap", Ether()/IP()/UDP()/((60-20-8-14)*"\0"))

With this ethermin.pcap, netmapfwd has performance of about 10 MPPS with the patch to remove setting of nr_rx_slots and nr_tx_slots to the most optimal values. ODP's odp_l2fwd_simple has performance of just about 5.5 MPPS.

I also tried modifyng netmapreplay.c to not have the nr_tx_slots / nr_rx_slots settings. Now perf of my application with large packets is 2.9 MPPS, perf of odp_l2fwd_simple is 1.3 MPPS. With small packets, perf of my application is 7.1 MPPS and perf of odp_l2fwd_simple is 2.8 MPPS.

Clearly, the overhead of ODP shouldn't be that large! And I'm using the latest version of ODP.

This isn't just limited to the simplest of possible applications. I have also made a TCP SYN proxy using netmap (https://github.com/jmtilli/nmsynproxy) that does some packet processing without just forwarding all packets in a dumb manner. Performance of ODP version is 1.4 MPPS and performance of raw netmap version is 2.4 MPPS (71% performance benefit). To test with netmap, edit conf.txt to have a row with "test_connections;" (without quotes), and run in different terminal windows:

    sudo ./nmsynproxy/synproxy/nmsynproxy vale0:1 vale1:1
    sudo ./nmsynproxy/synproxy/netmapsend vale0:0

Then compile with ODP by editing opts.mk to have:

    WITH_NETMAP=yes
    NETMAP_INCDIR=/wherever/is/netmap/sys
    WITH_ODP=yes
    ODP_DIR=/wherever/odp/is/installed

Also, LIBS_ODPDEP may need to be set in opts.mk to fix any possible linking issues. Then run in different terminal windows:

    sudo ./nmsynproxy/synproxy/odpsynproxy vale0:1 vale1:1
    sudo ./nmsynproxy/synproxy/netmapsend vale0:0

...and you observe the performance difference (although by editing netmapsend and nmsynproxy to not have the nr_tx_slots and nr_rx_slots code lines, performance of the netmap version drops to 1.55 MPPS, and performance of ODP version drops to 1.0 MPPS -- still 55% performance benefit of raw netmap).

**Comment by apalos** [comment]
Hello,

In Platform/linux-generic/pktio/netmap.c there's a select() call with 0
timeout. Can you please change that (any non 0 value would do) and repeat?

Regards
Ilias

**Comment by jmtilli** [comment]
I tried it but 1 usec timeout totally kills performance (odpsynproxy went from 1 MPPS to 0.25 MPPS because of the change). So it has to be 0 usec.

But perhaps this experiment could indicate where the problem might be...

**Comment by apalos** [comment]
I think i observed a performance increase on some random tests i did a few
months ago, using a timeout of 1 second. Not sure if i also tried with 1
usec.

Netmap can either poll or send an ioctl to "kick" the queues. We are using
polling at the moment. Perhaps giving the ioctl a shot would worth the
trouble.

**Comment by jmtilli** [comment]
Another recent theory of mine is that this is caused by odp_packet_t allocator and additional memory copies. Just for fun, I tested what would happen if the packet deallocation was restricted to happen in the same order as packet allocation. Netmap uses internally ring allocators, meaning you must deallocate netmap's packet descriptors in the same order they are allocated. Because ODP does not require the same order here, ODP cannot do zero-copy netmap input and must therefore allocate separate memory blocks (requiring CPU time), and memory-copy the packet data to said separate memory blocks (requiring even more CPU time).

The result of my experiment is called L Data Plane (LDP), kind of a competitor to ODP, supporting mainly netmap packet I/O (with zero-copy input) but also sockets for emergencies, DPDK in case somebody really wants to and many other mechanisms such as null/.pcap and also I/O via ODP. LDP can be found here: https://github.com/jmtilli/pptk/tree/master/ldp

For the simplest of applications where packets can be deallocated in the same order they were allocated, LDP may be a better fit than ODP, if the obvious code quality issues are sorted (I hacked it up in a week so I didn't have time to write code of excellent quality). But once you start to demand things like QoS network schedulers, it is not so obvious anymore that packets can be deallocated in the same order they were allocated.

With ldpfwd, I can obtain 4.19 MPPS on the laptop where netmap forwarding obtained 4.56 MPPS and ODP's l2fwd only 2.13 MPPS. All of these used VALE via netmap.

I guess requiring to deallocate packets in the exact same order they were allocated would be such a major architectural change to ODP that it will never happen, and therefore, netmap zero-copy input will also never happen. Also, I don't believe memcpy can be optimized more than it has already been optimized. Therefore, the place to look at for potential improvements would be odp_packet_t allocator.

**Comment by Bill-Fischofer-Linaro** [comment]
@jmtilli Interesting. The effects of zero-copy vs. non-zero-copy are going to be more pronounced on slower machines like laptops. I believe @apalos as part of the net_mdev work has observed that it hardly makes any difference for server-class machines. 

ODP (linux-generic) currently uses rings for package allocation, however there is no implied ordering. It's not obvious why this is related to zero-copy since the DPDK zero-copy support doesn't require this. Can you elaborate?

**Comment by jmtilli** [comment]
Netmap has head, cur and tail pointers in the ring. Head is the first user slot (i.e. oldest packet the userspace is going to free next), cur is the wakeup point (i.e. first packet userspace hasn't seen) and tail is the first kernel slot. Because of this ring structure, packets must be freed starting from the head slot, i.e. the oldest packet. Currently, ODP allocates separate buffers, memory-copies the data from the netmap buffers to its own buffers and frees the netmap buffers -- in the same order they were allocated. The user application may or may not free ODP buffers in the same order they were allocated.

The buffers in the netmap ring are fixed. ODP probably uses a ring of pointers to packets. This means when allocating a packet, it is removed from the ring, and when deallocating a packet, it is added again to the ring. In netmap, the buffers stay in the ring even after the userspace has obtained the packet from the kernel. In ODP, in contrast, packets have no specific fixed location in the ring.

I'm not actually sure if it's possible to make netmap ring more like ODP rings by changing the data buffer pointers. Probably only the netmap developers know the answer to that.

DPDK zero-copy support indeed does not require ordering. This is because DPDK has its own mbuf allocator, and I believe ODP uses that for the packet buffers.

But an interesting theory that server class machines won't benefit that much from zero-copy. I happen to have an access to a server with 6 years old CPU. I could check the performance there.

**Comment by jmtilli** [comment]
I investigated the performance of ODP's l2fwd more with VALE. Buffer/packet allocation and deallocation was 8.65% of total, memory copy was 31.88% of total. This was on the laptop.

On the server, I obtained 2.7 MPPS from odp_l2fwd and 4.3 MPPS from ldpfwd. So the difference on server-class machines is definitely smaller but it's still there. The server had 46% memcpy and 4.61% allocators.

**Comment by Bill-Fischofer-Linaro** [comment]
@jmtilli Can this issue now be closed since PR #516 has been merged to address this?

**Comment by jmtilli** [comment]
Considering that PR #516 has been merged to improve VALE performance and PR #559 has been opened to explain more potential improvements (that I fear won't be implemented in ODP), I agree this can be closed.
