### ISSUE TITLE
error when compiling odp

### ISSUE THREAD

**Issue by bestgen** [Linaro/odp#555]
Hello. When I execute "./configure" beneath the odp-master path, it shows errors below:

```
checking for __int128... yes
checking whether -latomic is needed for 128-bit atomic built-ins... yes
checking for __atomic_exchange_16 in -latomic... no
configure: error: in `/home/admin/Downloads/odp-master':
configure: error: __atomic_exchange_16 is not available
```

I have installed libatomic but the error still exists.
Does anyone have some ideas about how to solve this problem? Thanks.

**Comment by muvarov** [comment]
what dow you use? gcc or clang? and which version? Which version of ODP? Current master branch?

**Comment by bestgen** [comment]
Thanks for reply. I use gcc 4.8.5, ODP with the latest version v1.18.0.1
