### ISSUE TITLE
scalable scheduler does not respect timers.

### ISSUE THREAD

**Issue by nysan** [Linaro/odp#597]
All schedulers except the scalable scheduler seem to respect scheduled timer queues.
Is this by design or mistake ?

The below diff seem to "fix" the functional issue, please note that I have not measured the effects on scalability for this diff.
```

--- a/platform/linux-generic/odp_schedule_scalable.c
+++ b/platform/linux-generic/odp_schedule_scalable.c
@@ -23,6 +23,7 @@
 #include <odp_debug_internal.h>
 #include <odp_ishm_internal.h>
 #include <odp_ishmpool_internal.h>
+#include <odp_timer_internal.h>
 
 #include <odp_align_internal.h>
 #include <odp_buffer_inlines.h>
@@ -889,6 +890,8 @@ static int _schedule(odp_queue_t *from, odp_event_t ev[], int num_evts)
        ts = sched_ts;
        atomq = ts->atomq;
 
+       timer_run();
+
        /* Once an atomic queue has been scheduled to a thread, it will stay
         * on that thread until empty or 'rotated' by WRR
         */
```

**Comment by Bill-Fischofer-Linaro** [comment]
@brbrooks Can you comment on this?

**Comment by brbrooks** [comment]
@nysan by mistake. Your patch is correct. Will you follow through with it as a GitHub pull request?

**Comment by muvarov** [comment]
I think that this patch is ok. Interesting that our validation tests did not capture this issue. And it's not easy to create such test.

**Comment by brbrooks** [comment]
I am in the process of submitting a PR for this.

**Comment by brbrooks** [comment]
#603 - linux-generic: schedule: call timer_run() in scalable scheduler

**Comment by Bill-Fischofer-Linaro** [comment]
@nysan PR #603 has been merged to fix this problem. OK to close this issue? Thanks.

**Comment by nysan** [comment]
OK.

Thanks,
David

Den tis 29 maj 2018 22:00Bill Fischofer <notifications@github.com> skrev:

**Comment by Bill-Fischofer-Linaro** [comment]
Closing this issue as it is now resolved.
