### ISSUE TITLE
Traffic manager validation test fails randomly on ThunderX2

### ISSUE THREAD

**Issue by matiaselo** [Linaro/odp#654]
While running ODP linux-generic on ThunderX2 platform (Ubuntu 16.04 - 4.13.0-19.22-generic) the traffic manager validation test fails quite randomly (~20% of runs).

Collection of errors from failed runs:
```
  Test: traffic_mngr_test_shaper ...traffic_mngr.c:2531:test_shaper_bw():min=1 avg_rcv_gap=6125 max=13473 std_dev_gap=4982
traffic_mngr.c:2534:test_shaper_bw():  expected_rcv_gap=10000 acceptable rcv_gap range=7998..12502
traffic_mngr.c:2552:test_shaper_bw():agv_rcv_gap=6125 acceptable rcv_gap range=7998..12502
FAILED
    1. traffic_mngr.c:3854  - !odp_cunit_ret(test_shaper_bw("bw1", "node_1_1_1", 0, MBPS * 1))


  Test: traffic_mngr_test_shaper ...traffic_mngr.c:2531:test_shaper_bw():min=1 avg_rcv_gap=1941 max=3999 std_dev_gap=1834
traffic_mngr.c:2534:test_shaper_bw():  expected_rcv_gap=1000 acceptable rcv_gap range=798..1252
traffic_mngr.c:2552:test_shaper_bw():agv_rcv_gap=1941 acceptable rcv_gap range=798..1252
traffic_mngr.c:2559:test_shaper_bw():std_dev_gap=1834 >  expected_rcv_gap_us=1000
FAILED
    1. traffic_mngr.c:3862  - !odp_cunit_ret(test_shaper_bw("bw10", "node_1_1_1", 2, 10 * MBPS))


  Test: traffic_mngr_test_shaper ...traffic_mngr.c:2531:test_shaper_bw():min=3996 avg_rcv_gap=18023 max=51818 std_dev_gap=12944
traffic_mngr.c:2534:test_shaper_bw():  expected_rcv_gap=10000 acceptable rcv_gap range=7998..12502
traffic_mngr.c:2552:test_shaper_bw():agv_rcv_gap=18023 acceptable rcv_gap range=7998..12502
traffic_mngr.c:2559:test_shaper_bw():std_dev_gap=12944 >  expected_rcv_gap_us=10000
traffic_mngr.c:2502:test_shaper_bw():Sent 50 pkts but only 19 came back
traffic_mngr.c:2502:test_shaper_bw():Sent 50 pkts but only 20 came back
traffic_mngr.c:2502:test_shaper_bw():Sent 50 pkts but only 11 came back
FAILED
    1. traffic_mngr.c:3854  - !odp_cunit_ret(test_shaper_bw("bw1", "node_1_1_1", 0, MBPS * 1))
    2. traffic_mngr.c:3858  - !odp_cunit_ret(test_shaper_bw("bw4", "node_1_1_1", 1, 4 * MBPS))
    3. traffic_mngr.c:3862  - !odp_cunit_ret(test_shaper_bw("bw10", "node_1_1_1", 2, 10 * MBPS))
    4. traffic_mngr.c:3866  - !odp_cunit_ret(test_shaper_bw("bw40", "node_1_1_1", 3, 40 * MBPS))
```
Any ideas what could be causing this?

**Comment by Bill-Fischofer-Linaro** [comment]
Discussed this with Barry. Would like to know more about the test setup. Is this make check or something else? Also link speeds. Timing checks may not be appropriate for higher-end systems.

**Comment by matiaselo** [comment]
> Discussed this with Barry. Would like to know more about the test setup. Is this make check or something else? Also link speeds. Timing checks may not be appropriate for higher-end systems.

Make check, so no physical links are used.

**Comment by Bill-Fischofer-Linaro** [comment]
Had a call with Barry this afternoon. Some quick thoughts from him:

If `odp_time_local()` is miscalibrated that could cause some issues (timing errors). Tests only use one core so it's not clear why this should care about high core count unless they are being load balanced via RSS or something else? The loopback tests assume an emulated serial link. If loopback packets are being load-balanced by the scheduler to many different cores that might be a corner case that the test doesn't handle properly. Test assumes loopback packets are coming to a single queue/core. The test only sends 50 packets so if they are distributed across many cores it's difficult to do meaningful statistical analysis. Test assumes local time is the same on all cores.

Two errors: Statistical aspect and dropped packets. For dropped packets Barry has no immediate ideas. 

Barry is out tomorrow but should be available next week so we can cover this in more detail at next week's ODP public call.

**Comment by matiaselo** [comment]
> If odp_time_local() is miscalibrated that could cause some issues (timing errors). 

This seems to be the case. After disabling HW time the test is now passing every time.
