### ISSUE TITLE
webhook for auth is not working

### ISSUE THREAD

**Issue by muvarov** [Linaro/odp#712]
github scripts stopped working due to missing autorization in scripts:
https://github.com/muvarov/githubscripts
for example:
gh-hook-mr.py

It's not clear what actually goes on but now I get following error:
Traceback (most recent call last):
  File "gh-hook-mr.py", line 131, in <module>
    issue.edit(title="[PATCH v%d] %s" % (version, title))
  File "/usr/local/lib/python2.7/dist-packages/github3/decorators.py", line 37, in auth_wrapper
    raise error_for(r)
github3.exceptions.AuthenticationFailed: 401 Requires authentication

I.e. on 
issue.edit(title="[PATCH v%d] %s" % (version, title))
Scripts errored with Authentication error.
I tried both:
gh = login(gh_login, password=gh_password)
or
gh = login(token="my tocken here")
results is the same.

2 factor auth is turned off.

**Comment by bhcopeland** [comment]
Token is not a supported method ( https://developer.github.com/v3/oauth_authorizations/#deprecation-notice )

Personally I when using github I use a oauth token:

`def _get(url):
    headers = {'Authorization': 'token %s' % settings.GITHUB_OAUTH_TOKEN}
    request = urllib2.Request(url, headers=headers)
    try:
        return urllib2.urlopen(request)
    except urllib2.HTTPError as e:
        log.error('HTTP_%d while GETing %s:\n %s',
                  e.getcode(), url, e.readlines())
        sys.exit(1)
`

**Comment by muvarov** [comment]
I create test Oauth token. But the same error exist. And auth callback is not called. I think it has not be called. But 
```
auth = github3.github.GitHub.authorize(gh, gh_login, gh_password, scopes=my_scopes,
        note='odpauth',
        client_id='33530f79df76b30ba1f8', client_secret='9c10ac09feadb14ffa2ce9fad35941e6bfb5667f')
print auth.new_session()
<github3.session.GitHubSession object at 0x7f819429149


Traceback (most recent call last):
  File "gh-hook-mr.py", line 136, in <module>
    issue.edit(title="[PATCH v%d] %s" % (version, title))
github3.exceptions.AuthenticationFailed: 401 Requires authentication
```

**Comment by muvarov** [comment]
I think I resolved this issue. Added change to githubscripts repo.
